export const USER_ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  AGENT: 'AGENT',
};

export const WARRANTY_STATUS = {
  ACTIVE: 'ACTIVE',
  EXPIRING_SOON: 'EXPIRING_SOON',
  EXPIRED: 'EXPIRED',
};

export const EXPIRING_SOON_DAYS = 7;

export const MAINTENANCE_TYPES = {
  REPAIR: 'REPAIR',
  MAINTENANCE: 'MAINTENANCE',
  INSPECTION: 'INSPECTION',
  REPLACEMENT: 'REPLACEMENT',
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};
